D9 number guessing game
ArchismwanChatterjee/C pull request #10
Opened 2023-03-29 17:49 UTC by karan8404

This approach seems more visualizable. Inform me if I should instead stick to the question(and do that on top of this approach or scrap this approach altogether)

2023-04-01 04:14 UTC, Gadzrux commented
I would say stick to the format in the question

2023-04-03 14:51 UTC, Gadzrux requested changes

2023-04-03 14:51 UTC, Gadzrux commented on A/D9/number_guessing_game.c
when the numbers are in the correct position, the numbers don't show as correct anymore.
for example:
Generating a Random Number!...
Random Number Genarated!...
You have 5 Attempts to find the number.

Enter your guess[A 4 digit number]
1234
2 numbers are correct and 0 numbers are in correct position
Result:[x->not present , *->present , _->proper position]
1 2 3 4
* x x *

Incorrect Guess...4 Attempts left!

Enter your guess[A 4 digit number]
1456
3 numbers are correct and 0 numbers are in correct position
Result:[x->not present , *->present , _->proper position]
1 4 5 6
* * x *

Incorrect Guess...3 Attempts left!

Enter your guess[A 4 digit number]
4167
0 numbers are correct and 3 numbers are in correct position
Result:[x->not present , *->present , _->proper position]
4 1 6 7
_ _ _ x

Incorrect Guess...2 Attempts left!

Enter your guess[A 4 digit number]
4168
0 numbers are correct and 3 numbers are in correct position
Result:[x->not present , *->present , _->proper position]
4 1 6 8
_ _ _ x

Incorrect Guess...1 Attempts left!

Enter your guess[A 4 digit number]
4169
0 numbers are correct and 3 numbers are in correct position
Result:[x->not present , *->present , _->proper position]
4 1 6 9
_ _ _ x

Incorrect Guess...0 Attempts left!
Run out of attempts.. You Lost!. The number was : 4160

sorry for the format issue, md files have different meaning for characters like star.The entire code is working fine just work on the problem mentioned above

2023-04-03 14:51 UTC, Gadzrux commented on A/D10/merge_sorted.c
a very elegant solution, loved it.

2023-04-05 13:07 UTC, Gadzrux commented
resolve conflicts

2023-04-07 19:33 UTC, karan8404 commented on A/D9/number_guessing_game.c
That was intentional but i will change it anyway if it's better this was

2023-04-11 06:00 UTC, closed without merging